-- A Patch is a collection of smol programms ('SmolP').
local class = require('wm2.lib.middleclass')
local WM2Object = require('wm2.wm2object')

local Patch = class('Patch', WM2Object)

function Patch:initialize(...)
    WM2Object.initialize(self)
    local arg = {...}
    self.smolp_count = 0
    self.smolps = {}
    self.csound_orchestra = self.get_csound_orchestra_header()
    local instr_id = 0
    for _, smolp in pairs(arg) do
        self.smolps[smolp.smolid] = smolp
        self.smolp_count = self.smolp_count + 1
        if smolp.orchestra then
            self.csound_orchestra = self.csound_orchestra .. '\n' .. smolp:orchestra()
            smolp.instr_id = instr_id
            instr_id = instr_id + 1
        end
    end
end

function Patch:__tostring()
    return "Patch()"
end

function Patch:get_csound_orchestra_header()
    return [[
;; Auto-generated by wm2.Patch.get_csound_orchestra_header
0dbfs = 1
    ]]
end

return Patch
